AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: System for automatically deleting access keys on a schedule
  
Globals:
  Function:
    Timeout: 10

Parameters:
  SchedulerCron:
    Type: String
    Description: Cron expression for AutoDeleteAccessKeysEventScheduler
    Default: cron(0 */2 * * ? *)

Resources:
  AutoDeleteAccessKeysFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !GetAtt AutoDeleteAccessKeysLambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        EventBridgeRule:
          Type: Schedule
          Properties:
            Name: AutoDeleteAccessKeysScheduledEvent
            Schedule: !Ref SchedulerCron

  AutoDeleteAccessKeysLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'AutoDeleteAccessKeysLambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 'AutoDeleteAccessKeysLambdaExecutionPolicy'          
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Join
                  - ''
                  - - "arn:aws:logs:"
                    - !Ref "AWS::Region"
                    - ":"
                    - !Ref "AWS::AccountId"
                    - ":*"
              - Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Join
                  - ''
                  - - "arn:aws:logs:"
                    - !Ref "AWS::Region"
                    - ":"
                    - !Ref "AWS::AccountId"
                    - ":log-group:/aws/lambda/*:*"
              - Effect: Allow
                Action:
                  - iam:DeleteAccessKey
                  - iam:ListUsers
                  - iam:ListAccessKeys
                Resource: '*'